# Example configuration file for rstar-arc
# All parameters are optional and will override defaults

# Task parameters
data-folder: "data_sample/training"
task-name: "8be77c9e"

# Model parameters
policy-model: "Qwen/Qwen2.5-Coder-7B-Instruct"
pp-model: "Qwen/Qwen2.5-Coder-7B-Instruct"
max-tokens: 2048

# Search parameters
search-mode: "mcts"  # Options: beam_search, mcts
max-depth: 10
temperature: 0.7

# System parameters
gpus: 1
dtype: "bfloat16"  # Options: float16, bfloat16
seed: 42

# Runtime parameters
verbose: true
# Uncomment to run deterministic mode
# deterministic: true
# Uncomment to provide a hint
# hint: "Try using pattern matching"
