# Example configuration file for rstar-arc
# All parameters are optional and will override defaults

# Task parameters
task-name: "8be77c9e"

# Model parameters

# Search parameters
search-mode: "mcts"
max-depth: 9
num-simulations: 64
c-puct: 2.0
branching-factor: 6

# System parameters


# Runtime parameters
log-level: "DEBUG"
