# Example configuration file for rstar-arc
# All parameters are optional and will override defaults

# Task parameters
task-name: "8be77c9e"

# Model parameters


# Search parameters
search-mode: "beam_search"  # Options: beam_search, mcts
max-depth: 5
beam-width: 2  # Number of "best candidates" to keep after each step
branching-factor: 2  # Number of candidates to generate per node

# System parameters


# Runtime parameters
log-level: "DEBUG"

