search-mode: "smcts"
log-level: "DEBUG"

policy-model: "Qwen/Qwen2.5-Coder-32B-Instruct"
policy_temperature: 1.0

data-folder: "/home/piroth/rstar-arc/data_sample/easy"

branching-factor: 8
max-depth: 8
num-simulations: 16


