search-mode: "mcts"
log-level: "DEBUG"

policy-model: "Qwen/Qwen2.5-Coder-32B-Instruct"
policy_temperature: 1.0

data-folder: "/home/piroth/rstar-arc/data_sample/very_easy"

branching-factor: 10
max-depth: 8
num-simulations: 16


