search-mode: bs
log-level: INFO

data-folder: /itet-stor/piroth/net_scratch/task_data/training_extended

examples-mask: [ true, true, false ]
policy-temperature: 1.0

beam-width: 12
branching-factor: 12
max-depth: 12

batch-size: 10

