search-mode: "custom"
log-level: "DEBUG"

data-folder: "/home/piroth/rstar-arc/data_sample/easy"

policy-temperature: 1

examples-mask: [ false, true, true ]

num-simulations: 8
branching-factor: 12
max-depth: 12

