search-mode: "custom"
log-level: "DEBUG"

data-folder: "/home/piroth/rstar-arc/data_sample/easy"

example-names: [ "6d0aefbc", "1cf80156" ]
rotate-example: true

variable-temperature: true
min-policy-temperature: 0.7
max-policy-temperature: 1.1

save-sft-data: false

num-simulations: 8
branching-factor: 4
max-depth: 12



