search-mode: "custom"
log-level: "INFO"

save-for-visualization: false
round-number: 0

# TODO: test whether the non-instruct version works better
policy-model: "Qwen/Qwen2.5-Coder-14B-Instruct"
max-model-len: 32768

data-folder: "/itet-stor/piroth/net_scratch/task_data/training"

# example-names
rotate-example: true

variable-temperature: true
min-policy-temperature: 0.7
max-policy-temperature: 1.1

save-sft-data: true

num-simulations: 64
branching-factor: 8
max-depth: 20


