search-mode: "custom"
log-level: "DEBUG"

policy-model: "Qwen/Qwen2.5-Coder-14B-Instruct"
max-model-len: 32768

data-folder: "/home/piroth/rstar-arc/data_sample/easy"

# example-names
rotate-example: true

variable-temperature: true
min-policy-temperature: 0.7
max-policy-temperature: 1.1

save-sft-data: true

num-rollouts: 8
branching-factor: 8
max-depth: 20


