search-mode: "custom"
log-level: "DEBUG"

data-folder: "/home/piroth/rstar-arc/data_sample/easy"

policy-temperature: 1.0

examples-mask: [ false, true, true ]

num-simulations: 4
branching-factor: 12
max-depth: 10

