search-mode: "custom"
log-level: "INFO"

save-for-visualization: false
round-number: 0
solve-only-unsolved: true

policy-model: "Qwen/Qwen2.5-Coder-14B-Instruct"
max-model-len: 49152

data-folder: "/itet-stor/piroth/net_scratch/task_data/training_extended"

num-examples: 22
example-names: [["6d0aefbc", "1cf80156"], ["06df4c85"], ["3e980e27"], ["1f0c79e5"], ["8f2ea7aa"], ["9aec4887"], ["5c2c9af4"], ["045e512c"], ["08ed6ac7"], ["e3497940"], ["e26a3af2"], ["72ca375d"], ["28e73c20"], ["10fcaaa3"], ["150deff5"], ["228f6490"], ["00d62c1b"], ["63613498"], ["3631a71a"], ["4290ef0e"], ["0ca9ddb6"], ["27a28665"]]

rotate-example: true

variable-temperature: true
min-policy-temperature: 0.8
max-policy-temperature: 1.1

save-sft-data: true

num-rollouts: 44
branching-factor: 8
max-depth: 20

batch-size: 61

