search-mode: "custom"
log-level: "DEBUG"

save-for-visualization: false
round-number: 0

policy-model: "Qwen/Qwen2.5-Coder-14B-Instruct"
max-model-len: 32768
max-tokens: 16


data-folder: "/itet-stor/piroth/net_scratch/task_data/training"

example-names: [["6d0aefbc", "1cf80156"], ["00d62c1b"], ["e3497940"], ["8f2ea7aa"], ["3e980e27"], ["28e73c20"]]
rotate-example: true

variable-temperature: true
min-policy-temperature: 0.7
max-policy-temperature: 1.1

save-sft-data: false

num-rollouts: 20
branching-factor: 8
max-depth: 1


