search-mode: "custom"
log-level: "DEBUG"

data-folder: "/home/piroth/rstar-arc/data_sample/very_easy"

rotate-example: true

variable-temperature: true
min-policy-temperature: 0.7
max-policy-temperature: 1.1

save-sft-data: false

num-simulations: 16
branching-factor: 8
max-depth: 16



