search-mode: "mcts"
log-level: "INFO"

fine-tuned: true

save-for-visualization: true
round-number: 2
solve-only-unsolved: false
solutions-per-task: 16
save-sft-data: false

policy-model: "checkpoint-752"
max-model-len: 20480
dtype: "bfloat16"


data-folder: "/itet-stor/piroth/net_scratch/task_data/training"
sort-by-length: false

rotate-example: false

policy-temperature: 0.5

num-rollouts: 8

branching-factor: 8
max-depth: 16

batch-size: 45
