search-mode: "mcts"
log-level: "DEBUG"

fine-tuned: true

save-for-visualization: true
round-number: 2
solve-only-unsolved: false
solutions-per-task: 16

policy-model: "ft-Qwen2.5-Coder-1.5B-20480-5e-05"
use_reward_model: true
reward-model: "ft-Qwen2.5-Coder-1.5B-20480-5e-05"
max-seq-len: 20480
dtype: "bfloat16"


data-folder: "/home/piroth/rstar-arc/data_sample/very_easy"
sort-by-length: false

rotate-example: false

variable-temperature: false
policy-temperature: 0.5

save-sft-data: false

num-rollouts: 8

branching-factor: 8
max-depth: 12

