search-mode: "mcts"
log-level: "INFO"

fine-tuned: true

save-for-visualization: true
round-number: 6
solve-only-unsolved: false
solutions-per-task: 32
save-sft-data: true

policy-model: "final_policy_3B"
max-seq-len: 14336
max-tokens: 512
dtype: "bfloat16"

data-folder: "/home/piroth/rstar-arc/data_sample/easy"
sort-by-length: false
length-pre-filtering: true

variable-temperature: true
min-policy-temperature: 0.4
max-policy-temperature: 0.9

num-rollouts: 32
branching-factor: 8
max-depth: 16

batch-size: 40

