search-mode: "mcts"
log-level: "INFO"

fine-tuned: true

save-for-visualization: true
round-number: 2
solve-only-unsolved: false
solutions-per-task: 16

policy-model: "fine_tuned_0.5B"
max-model-len: 32768


data-folder: "/home/piroth/rstar-arc/data_sample/very_easy"
sort-by-length: false

rotate-example: false

variable-temperature: true
min-policy-temperature: 0.7
max-policy-temperature: 1.0

save-sft-data: false

num-rollouts: 8

branching-factor: 8
max-depth: 12

