search-mode: "bs"
log-level: "DEBUG"

fine-tuned: true

save-for-visualization: true
round-number: 3
solve-only-unsolved: false
solutions-per-task: 16
save-sft-data: true

policy-model: "barc_ft_1.5"
max-seq-len: 16384
dtype: "bfloat16"

data-folder: "/home/piroth/rstar-arc/data_sample/easy"
sort-by-length: false
length-pre-filtering: true

policy-temperature: 0.8

branching-factor: 8
beam-width: 8
max-depth: 12

batch-size: 8
