search-mode: "bs"
log-level: "INFO"

fine-tuned: true

save-for-visualization: true
round-number: 3
solve-only-unsolved: false
solutions-per-task: 16
save-sft-data: true

policy-model: "barc_ft_1.5"
max-model-len: 16384
dtype: "bfloat16"


data-folder: "/itet-stor/piroth/net_scratch/task_data/training"
sort-by-length: false

rotate-example: false

policy-temperature: 0.8

branching-factor: 8
max-depth: 12

batch-size: 20
