search-mode: "mcts"
log-level: "DEBUG"

fine-tuned: true

save-for-visualization: true
round-number: 2
solve-only-unsolved: false
solutions-per-task: 16

policy-model: "fine_tuned_1.5B"
max-model-len: 12288

sort-by-length: false

rotate-example: false

policy-temperature: 0.2

save-sft-data: false

num-rollouts: 8
branching-factor: 8
max-depth: 12
