search-mode: "mcts"
log-level: "DEBUG"

save-for-visualization: true
round-number: 2
solve-only-unsolved: false

policy-model: "Qwen/Qwen2.5-Coder-7B-Instruct"
max-model-len: 12288

policy-temperature: 0.8

save-sft-data: false

num-simulations: 8
branching-factor: 8
max-depth: 12
