search-mode: "mcts"
log-level: "INFO"

evaluation: true

fine-tuned: false
execute-in-subprocess: true

save-for-visualization: false
round-number: 25
solve-only-unsolved: false
# solutions-per-task: 32
save-sft-data: true

use-reward-model: false
policy-vram-percentage: 0.85
reward-batch-size: 1

policy-model: "Qwen/Qwen2.5-Coder-3B-Instruct"
max-seq-len: 20480
max-tokens: 512
dtype: "bfloat16"

data-folder: "/itet-stor/piroth/net_scratch/task_data/evaluation"
sort-by-length: false
length-pre-filtering: true

num-examples: 1
example-names: [["1cf80156"]]

variable-temperature: true
min-policy-temperature: 0.65
max-policy-temperature: 0.9

num-rollouts: 32
branching-factor: 8
max-depth: 16

batch-size: 40

