# Example configuration file for rstar-arc
# All parameters are optional and will override defaults

# Task parameters
task-name: "8be77c9e"

# Model parameters


# Search parameters
search-mode: "mcts"
max-depth: 6
num-simulations: 8
c-puct: 2.0
branching-factor: 2

# System parameters


# Runtime parameters
log-level: "DEBUG"

