search-mode: "mcts"
log-level: "INFO"

evaluation: false

fine-tuned: false
execute-in-subprocess: true

save-for-visualization: false
round-number: 23
solve-only-unsolved: false
# solutions-per-task: 32
save-sft-data: true

use-reward-model: true
policy-vram-percentage: 0.45
reward-batch-size: 1

policy-model: "Qwen/Qwen2.5-Coder-3B-Instruct"
reward-model: "final_reward_0.5B"
max-seq-len: 14336
max-tokens: 512
dtype: "bfloat16"

data-folder: "/itet-stor/piroth/net_scratch/task_data/training"
sort-by-length: false
length-pre-filtering: true

variable-temperature: true
min-policy-temperature: 0.65
max-policy-temperature: 0.9

num-rollouts: 32
branching-factor: 8
max-depth: 16

batch-size: 40

