search-mode: "mcts"
log-level: "INFO"
evaluation: true
round-number: 6

fine-tuned: true

policy-model: "final_policy_1.5B"
max-seq-len: 14336
max-tokens: 2048

length-pre-filtering: true

dtype: "bfloat16"


data-folder: "/itet-stor/piroth/net_scratch/task_data/evaluation"
sort-by-length: false

policy-temperature: 0.8

num-rollouts: 1024

batch-size: 50
