search-mode: "mcts"
log-level: "INFO"
evaluation: false
round-number: 6

fine-tuned: true

policy-model: "final_policy_1.5B"
max-seq-len: 14336
max-tokens: 2048

length-pre-filtering: true

dtype: "bfloat16"


data-folder: "/itet-stor/piroth/net_scratch/task_data/training"
sort-by-length: false

policy-temperature: 0.7

num-rollouts: 128
