search-mode: "mcts"
log-level: "INFO"

fine-tuned: true

policy-model: "barc_ft_1.5"
max-seq-len: 16384
max-tokens: 2048

length-pre-filtering: true

dtype: "bfloat16"


data-folder: "/itet-stor/piroth/net_scratch/task_data/evaluation"
sort-by-length: false

policy-temperature: 0.7

num-rollouts: 128
