log-level: INFO
round-number: 5

task-validation-fraction: 0.003
example-validation-num: 1
example-validation-threshold: 5
example-validation-probability: 0.01

max-seq-len: 14336

resume-from-checkpoint: false

fine_tuned: false
run-name: "better-ft-policy-3B"
policy-model: "Qwen/Qwen2.5-Coder-3B"
training-dataset-name: "policy_dataset_training.jsonl"
validation-dataset-name: "policy_dataset_validation.jsonl"
use-bf16: true
attn-implementation: "flash_attention_2"
torch-compile: false

full-finetune: true

train-on-prompts: false

learning-rate: 0.0000125
weight_decay: 0

per-device-train-batch-size: 1
per-device-eval-batch-size: 1
gradient-accumulation-steps: 32
num-train-epochs: 2
lr-scheduler-type: "cosine"
warmup-ratio: 0.1
logging-steps: 200
eval-steps: 400
save-steps: 400
gradient-checkpointing: true

report-to: "wandb"