log-level: INFO
round-number: 3

qualitative-eval: false

task-validation-fraction: 0.05
example-validation-num: 1
example-validation-threshold: 4

max-seq-len: 16384

policy-model: "Qwen/Qwen2.5-Coder-1.5B"
training-dataset-name: "policy_dataset.jsonl"
validation-dataset-name: "policy_dataset_validation.jsonl"
use-bf16: true
# attn-implementation: "flash_attention_2"

full-finetune: true
weight_decay: 0.00001
train-on-prompts: false

learning-rate: 0.00001

per-device-train-batch-size: 1
per-device-eval-batch-size: 1
gradient-accumulation-steps: 64
num-train-epochs: 2
lr-scheduler-type: "cosine"
warmup-ratio: 0.03
logging-steps: 50
eval-steps: 100
save-steps: 100
save-total-limit: 3
gradient-checkpointing: true

report-to: "wandb"
