log-level: INFO
round-number: 6

task-validation-fraction: 0.02
example-validation-num: 1
example-validation-threshold: 4
example-validation-probability: 0.05

max-seq-len: 14336

resume-from-checkpoint: false

full-finetune: true
reward-value-head-dropout: 0.05

reward-model: "/itet-stor/piroth/net_scratch/models/policy/final_policy_0.5B"
training-dataset-name: "reward_dataset_training.jsonl"
validation-dataset-name: "reward_dataset_validation.jsonl"
use-bf16: true
attn-implementation: "spda"
torch-compile: false

train-on-prompts: false

learning-rate: 0.00001
weight_decay: 0.01

per-device-train-batch-size: 1
per-device-eval-batch-size: 1
gradient-accumulation-steps: 256

num-train-epochs: 1

lr-scheduler-type: "cosine"
warmup-ratio: 0.1
logging-steps: 50
eval-steps: 100
save-steps: 100
save-total-limit: 2
gradient-checkpointing: true

report-to: "wandb"


