log-level: INFO
round-number: 3

qualitative-eval: false

task-validation-fraction: 0.05
example-validation-num: 1
example-validation-threshold: 5

max-seq-len: 16384

policy-model: "Qwen/Qwen2.5-Coder-7B"
training-dataset-name: "policy_dataset_training.jsonl"
validation-dataset-name: "policy_dataset_validation.jsonl"
use-bf16: true
attn-implementation: "flash_attention_2"
torch-compile: false

full-finetune: true
weight_decay: 0
train-on-prompts: false

learning-rate: 0.00001

per-device-train-batch-size: 1
per-device-eval-batch-size: 1
gradient-accumulation-steps: 64
num-train-epochs: 2
lr-scheduler-type: "cosine"
warmup-ratio: 0.05
logging-steps: 100
eval-steps: 200
save-steps: 200
save-total-limit: 3
gradient-checkpointing: true

report-to: "wandb"
